### ISSUE TITLE
Usage of std Mutex could case a deadlock in FirebaseAuth#start_key_update

### ISSUE THREAD

**Issue by stepan-romankov** [trchopan/firebase-auth#22]
this could cause a deadlock 
```rust
    async fn start_key_update(&mut self) {
    ...
    let mut verifier = verifier_ref.lock().unwrap();
```
especially when only one thread is configured for async Runtime

**Comment by trchopan** [comment]
In this case, there is no deadlock because you are not locking the mutex across a preemption point (await while holding the mutex lock). If a panic occurs, it will poison the mutex, leading to another thread panicking when calling lock().unwrap(), but it will not cause a deadlock.
I aware that it does not handle the exception case very well. I will try to use tokio::sync::Mutex in the next version.

**Comment by stepan-romankov** [comment]
I'm very novice in rust, but are you sure that dead lock will not happen in the single-threaded tokio runtime?

**Comment by trchopan** [comment]
Me too. I'm still learning the craft :D 
Still I not yet reproduce a deadlock so I think we are safe.
